services:
  - type: web
    name: tgju-telegram-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --threads 4 --timeout 120
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
      - key: FETCH_INTERVAL_SECONDS
        value: "300"
      - key: SHOW_IN_TOMAN
        value: "true"
